platform :ios, '6.0'
pod 'Mixpanel', '2.0.0'
pod 'DCIntrospect-ARC', '~> 0.0.3'
pod 'RestKit', '~> 0.22.0'
pod 'AMScrollingNavbar', '~> 0.4.1'
pod 'DejalActivityView', '~> 1.1'
pod 'EGOTableViewPullRefresh', '~> 0.1.0'
pod 'YIFullScreenScroll', '~> 1.2.1'
pod 'CURestKit'
pod 'JSONModel'
pod 'HPGrowingTextView', '~> 1.1'
pod 'GoldenFleece', '~> 1.1'
